cask_args appdir: '/Applications'

# Load cask skip list from ~/.localrc if not already in environment
if ENV['HOMEBREW_BUNDLE_CASK_SKIP'].nil? || ENV['HOMEBREW_BUNDLE_CASK_SKIP'].empty?
  localrc = File.expand_path('~/.localrc')
  if File.exist?(localrc)
    File.read(localrc).match(/^export HOMEBREW_BUNDLE_CASK_SKIP="([^"]*)"/) do |m|
      ENV['HOMEBREW_BUNDLE_CASK_SKIP'] = m[1]
    end
  end
end

brew 'atuin'
brew 'awscli'
brew 'bash'
brew 'bat'
brew 'btop'
brew 'cloudflared'
brew 'coreutils'
brew 'delta'
brew 'eza'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'grc'
brew 'hyperfine'
brew 'imagemagick'
brew 'jq'
brew 'mise'
brew 'openssl'
brew 'postgresql@18'
brew 'ripgrep'
brew 'sqlite'
brew 'starship'
brew 'tldr'
brew 'wget'
brew 'zoxide'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-fast-syntax-highlighting'

cask '1password'
cask 'audacity'
cask 'cloudflare-warp'
cask 'claude-code'
cask 'codex'
cask 'font-fira-code'
cask 'font-hack-nerd-font'
cask 'font-victor-mono'
cask 'garmin-express'
cask 'ghostty'
cask 'google-chrome'
cask 'google-drive'
cask 'grammarly-desktop'
cask 'keepingyouawake'
cask 'ngrok'
cask 'obsidian'
cask 'rectangle'
cask 'signal'
cask 'spotify'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'zoom'
