cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/fonts'

brew 'ack'
brew 'awscli'
brew 'bash-completion'
brew 'bash'
brew 'coreutils'
brew 'git-flow'
brew 'git'
brew 'grc'
brew 'htop'
brew 'imagemagick'
brew 'openssl'
brew 'wget'
brew 'zsh-completions'
brew 'zsh'

cask 'atom'
cask 'boostnote'
cask 'brave-browser'
cask 'dash'
cask 'docker'
cask 'evernote'
cask 'firefox'
cask 'font-fira-code'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'grammarly'
cask 'iterm2'
cask 'kap'
cask 'keepingyouawake'
cask 'omnigraffle'
cask 'postman'
cask 'sketchup'
cask 'skype'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'sublime'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
