#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
while IFS= read -r -d '' installer; do
  sh -c "${installer}"
done < <(find . -name install.sh -print0)
